### ISSUE TITLE
Question: Run Specflow tests in Xamarin.TestCloud

### ISSUE THREAD

**Issue by KarinBerg** [Geertvdc/BDDXamarin#1]
Hello Geert,
I saw your guest lecture on Xamarin University. It was very interessting but I still wondering if I can run Specflow tests which are not UI tests in the Xamarin Testcloud?

My Specflow tests are creating directly ViewModels and call methods on them. Is it also possible to run such tests in the test cloud? If yes how??? Could you give me a hint?

**Comment by Geertvdc** [comment]
Hi @KarinBerg, Testcloud is made to run UI tests, not unit tests. if you've created test to run on your viewmodels these tests are just C# unit tests and you can run them locally or on your buildserver. 

Why would you want to run them on Testcloud?

**Comment by KarinBerg** [comment]
We are developing a "Framework" (NuGet-Package) which implements all those stuff we need in many of our apps. This are things like calling REST-services, cache the data from the REST services, Retry mechanism, and so on. So we have a framework which consists of multiple portable class library projects. 

To guarantee that the framework is actually working on a iOS or Android device we had to create a simple Xamarin app which is using the framework via NuGet. Because this is awkward I was looking for a better way to test the main usecases of our framework on a real device. Since our main usecases are specified by gherkins and implemented via Specflow as tests, it would be cool to run this tests on real devices to really ensure it works on the target platform.

Since Specflow only works on a project which is targeting .NET (no portable class library) it seems there is no way to execute them on a device.

The only way to achive my goal is to use [XUnit for devices](https://github.com/xunit/devices.xunit). With that you can run XUnit tests in the Testcloud on real devices. But I have to implement new tests in a portable class library. I can not use the already existing Specflow tests.

I hope I could clarify what I want to achieve. :)

**Comment by Geertvdc** [comment]
@KarinBerg you could try to use Specflow.XUnit. haven't tried that yet. will give it a go myself as well.

https://www.nuget.org/packages/SpecFlow.xUnit/
